- README.md
- package-lock.json
- package.json
just general housekeeping. keeping the vuln's low.  (there are still 4, but updating them actually creates worse ones. for now.)
> update npm deps and org namespace in readme

- docker-compose.yaml
incorrectly overwrites /app dir with local dir contents in docker-compose file.
> docker fix

- Dockerfile
- package.json
to address the proxy.conf perm issue #53 in the docker container.
> proposed fix for #53

- Dockerfile
now just explicitly setting owner on proxy.conf.json to 1001:1001
> second try #53

- CONTRIBUTING.md
> issue-56 Add Community assets

- package.json
- src/app/services/entity-search.service.ts
* fix for spinner issue
* version bumped up to next release
#67 #69 
spinner was disappearing prematurely
> fix for gui spinner prematurely disappearing #67 #69

- package-lock.json
- package.json
- src/app/about/about.component.html
- src/app/about/about.component.scss
- src/app/about/about.component.ts
- src/app/app-routing.module.ts
- src/app/app.component.scss
- src/app/app.module.ts
- src/app/services/about.service.ts
- src/app/toolbar/toolbar.component.html
- src/app/toolbar/toolbar.component.scss
- src/app/toolbar/toolbar.component.ts
- src/tsconfig.app.json
- tsconfig.json
#68  on click of the powered by logo show dependency and diagnostic data.
to provide relevant dependency and server information.
> Show about info box

- .dockerignore
- CHANGELOG.md
- Makefile
- PULL_REQUEST_TEMPLATE.md
- README.md
> Issue-79 Refactor to template

- src/app/app.component.html
- src/app/app.component.scss
- src/app/graph/graph.component.ts
- src/app/search-results/search-results.component.html
- src/app/search-results/search-results.component.scss
- src/app/search-results/search-results.component.ts
- src/styles.scss
Issue number: #73 
requested feature.
navigating between textual search results and graph results.
> open search results in graph #73

- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/record/record.component.html
- src/app/record/record.component.scss
- src/app/record/record.component.ts
- src/app/services/entity-search.service.ts
- src/app/services/ui.service.ts
- src/app/toolbar/toolbar.component.html
- src/app/toolbar/toolbar.component.ts
Issue number: #83 
To allow users to search by:
* datasource + record id
* entity id
> Search by record Id or entity Id

- .github/workflows/cd-3hr-cron-test-debian-build.yml
- .github/workflows/cd-pr-test-debian-build.yml
- Makefile
Issue number: #92 
Implemented initial CD pipeline for pull request trigger
Standardizes CI/CD pipeline tool
> Issue 92.bryan nice

- README.md
- angular.json
- auth-server.js
- auth/auth.conf.json
- auth/auth.js
- auth/cors.conf.json
- auth/cors.conf.tmpl.json
- auth/csp.conf.js
- docker-compose.yaml
- inject-env.js
- package.json
- proxy.conf.tmpl.json
- src/index.html
- webserver.js
resolves #96 
To prevent and/or decrease potential XSS attack surface.
- Adds CSP(Content Security Policy) - enabled by default
- Adds CORS as option - disabled by default
- Prevents most non-origin or non-whitelisted script injection
- Prevents non-origin or non-whitelisted style injection
- Changes http proxy middleware error reporting to static message (prevents error response injection)
- Adds env/docker variable `SENZING_WEB_SERVER_CORS_ALLOWED_ORIGIN`
> Issue96.awinters.1

- CHANGELOG.md
> #102 Update for 1.2.1

- .github/workflows/cd-pr-test-debian-build.yml
Issue number: #111 
fixing tool chain breakage
> fixing reference

- package.json
Issue number: #116 
so that the commits currently in master have a last 1.x compatible release tag
> #116 update package number to 1.2.2

- package-lock.json
- package.json
- src/app/graph/graph.component.html
- src/app/graph/graph.component.ts
- src/app/services/entity-search.service.ts
Issue number: #115 
for compatibility with api spec 2.0.0
> 2.0.0 compatibility updates

- Dockerfile
Issue number: #120 
auth related runtime config files had incorrect permissions set
> #120 temp fix for perm on auth runtime files

- docker-compose.yaml
- docker-stack-ssl-basicauth.yml
- docker-stack-ssl.yml
- docker-stack.yml
> #128 Rename OS Environment Variables

- CHANGELOG.md
- package-lock.json
- package.json
resolves #132
updates:
- update rest-api-client-ng to 2.2.0 release
- update sdk-components-ng to 2.1.2 release
- update sdk-graph-components to 2.1.2 release
- run npm audit to resolve outstanding sec issues with third party deps
> #132 update @senzing packages to 2.1.2/2.2.0

- README.md
- docker-compose.yaml
- docker-stack-ssl-basicauth.yml
- docker-stack-ssl.yml
- docker-stack.yml
> #160 Update to senzingdata 2.0.0

- run/runtime.datastore.config.js
resolves #183 
to fix a bug where the startup routine was ignoring `SENZING_WEB_SERVER_URL` with regards to socket-proxy setup
> #180 fix for SENZING_WEB_SERVER_URL issue

- run/config-server/index.js
- run/runtime.datastore.config.js
- run/runtime.datastore.js
- run/utils.js
- run/webserver/index.js
- src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.ts
- src/app/admin/load/load.component.html
- src/app/common/stream-conn-dialog/stream-conn-dialog.component.html
- src/app/common/stream-conn-dialog/stream-conn-dialog.component.ts
- src/app/common/stream-load-queue-dialog/stream-load-queue-dialog.component.ts
- src/app/common/stream-load-queue-dialog/stream-load-queue-info.component.ts
- src/app/services/admin.bulk-data.service.ts
- src/app/services/config.service.ts
- src/app/services/websocket.service.ts
resolves #185 
to support stream loading when user has set `SENZING_WEB_SERVER_VIRTUAL_PATH` env variable or set the `virtualPath` cmdline variable
allows user to use stream loading when webapp is being served from a virtual directory path ie `/app`
> virtual directory stream loading fixes

- src/app/common/streaming-file-record-parser.ts
- src/app/workers/stream-reader.worker.ts
resolves #200 
parser would hiccup on opening bracket `[` char in `.json` file
parser improvement
> #200 handle jsonl line endings inside .json encapsulation

- package.json
resolves #188
just for "best practice"
> added mit license to package.json

- Dockerfile
- Makefile
- src/app/admin/admin.module.ts
- src/app/admin/bulk-data/admin-bulk-data-analysis-summary.component.html
- src/app/admin/bulk-data/admin-bulk-data-analysis.component.html
- src/app/admin/bulk-data/admin-bulk-data-analysis.component.ts
- src/app/admin/bulk-data/admin-bulk-data-load-report.component.html
- src/app/admin/bulk-data/admin-bulk-data-load-summary.component.html
- src/app/admin/bulk-data/admin-bulk-data-load.component.ts
- src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.html
- src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.ts
- src/app/admin/bulk-data/admin-bulk-data-stream-load-report.component.html
- src/app/admin/bulk-data/admin-bulk-data-stream-load-report.component.scss
- src/app/admin/bulk-data/admin-bulk-data-stream-load-report.component.ts
- src/app/admin/load/load.component.html
- src/app/common/streaming-file-record-parser.ts
- src/app/services/admin.bulk-data.service.ts
- src/app/services/websocket.service.ts
- src/app/workers/stream-reader.worker.ts
resolves #217 
To allow users to load CSV files via SQS.
adds CSV import to stream loading
> Issue217.awinters.1

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/common/alert-dialog/alert-dialog.component.html
- src/app/common/alert-dialog/alert-dialog.component.scss
- src/app/common/alert-dialog/alert-dialog.component.ts
resolves #226 
So that users would get some sort of message when a entity specified by their search returns 404
search by id messaging
> Search By Id should display message when no entity is found

- CHANGELOG.md
> Issue239.awinters.1

- package-lock.json
- package.json
resolves #246
dependency security updates
- [Regular Expression Denial of Service in postcss](https://github.com/advisories/GHSA-566m-qj78-rww5)
- [Prototype Pollution in node-forge debug API.](https://github.com/advisories/GHSA-5rrq-pxf6-6jx5)
- [URL parsing in node-forge could lead to undesired behavior.](https://github.com/advisories/GHSA-gf8q-jrpm-jvxq)
- [Exposure of Sensitive Information to an Unauthorized Actor  in nanoid](https://github.com/advisories/GHSA-qrpm-p2h7-hrv2)
- [Open Redirect in node-forge](https://github.com/advisories/GHSA-8fr3-hfg3-gpgp)
> #246 dependency security updates

- CHANGELOG.md
- Dockerfile
- package-lock.json
- package.json
- src/app/graph/graph.component.html
- src/app/graph/graph.component.ts
Issue number: #256 
code was referencing syntax for newer dependency version. When using the older version specified in the package/package-lock.json a fatal error would be encountered causing the webapp not to run.
stability
> Issue256.awinters.1

- package-lock.json
- package.json
- src/app/detail/detail.component.html
resolves #261 
Enables the "Why" functionality for the entity detail view
users can now see the why report for records in an entity, or all of the records for an entity together.
> #261 enable Why function for entity detail

- src/app/admin/bulk-data/admin-bulk-data-load.component.ts
- src/app/app.module.ts
- src/app/common/stream-load-queue-dialog/stream-load-queue-dialog.component.html
- src/app/common/streaming-file-record-parser.ts
- src/app/services/admin.bulk-data.service.ts
- src/app/services/websocket.service.ts
- src/app/workers/stream-reader.worker.ts
resolves #263 
Firefox using stream loading would display an error on connection close regardless of whether or not the request had completed successfully
browser compatibility
> #263 fix for stream loading in FireFox

- src/app/scss/styles.scss
resolves #274 
layout wrapping fix for match key chips
> #274 graph match key chips layout fix

- README.md
- docker-compose.yaml
- docker-stack-ssl-basicauth.yml
- docker-stack-ssl.yml
- docker-stack.yml
resolves #276 
- change default value of data dir mapping from `2.0.0` to `3.0.0`
- change default version of senzing-api-server from `2.0.1` to `3.0.1`
> #276 data updated to 3.0.0

- src/app/toolbar/toolbar.component.html
- src/app/toolbar/toolbar.component.ts
resolves #299 
The "Print to PDF" menu option should be removed since it doesn't work.
> #299 removing the print to pdf option

- angular.json
- package-lock.json
- package.json
- src/app/graph/graph.component.html
- src/app/graph/graph.component.ts
resolves #301 
sdk components needed an update to roll in fixes.
> #301 components updated to beta channel

- package-lock.json
- package.json
- src/app/about/about.component.html
resolves #301
sdk-components-ng updated to beta 2
bugfixes. dependency updates.
> #301 sdk-components-ng updated to beta 2

- CHANGELOG.md
- Dockerfile
- package-lock.json
- package.json
> updated for 2.7.0

- CHANGELOG.md
- Dockerfile
- package-lock.json
- package.json
> #345 updated sdk-components-ng@5.1.0

- docker-compose.yaml
> #382 Update network

- CHANGELOG.md
- Dockerfile
- README.md
> #386 Prepare for versioning

- package-lock.json
- package.json
- src/app/graph/graph.component.html
- src/app/graph/graph.component.scss
- src/app/graph/graph.component.ts
resolves #355 
newest @senzing/sdk-components-ng@5.1.1-beta.2
newest features/bugfixes
> Issue355.awinters.2

- src/app/services/prefs-manager.service.ts
- src/app/services/ui.service.ts
resolves #398 
to keep application UI state across page refresh
user experience
> #398 save application UI state across page refresh/tabs

- README.md
> #440 Update links

- .gitignore
- CHANGELOG.md
> #446 Prepare for versioned release

- CHANGELOG.md
> #475 updated for 2.9.0

- .github/workflows/test-npm.yaml
- package-lock.json
- package.json
- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/search-results/search-results.component.ts
- src/app/services/entity-search.service.ts
resolves #385 
the search results would be redirected to an error page on page refresh.
page now pulls last search params from app local storage if keys match
> session persistent search result urls

- .github/workflows/docker-push-containers-to-dockerhub.yaml
- CHANGELOG.md
- Dockerfile
> #494 Prepare for versioned release

- CHANGELOG.md
- package-lock.json
- package.json
resolves #510 
dependency updates
security
> #510 dependency updates

- .github/linters/.yaml-lint.yml
- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-app-server-dependabot.yaml
- .github/workflows/add-to-project-app-server.yaml
- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/lint-workflows.yaml
- .github/workflows/test-npm.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 add linting

- .github/workflows/test-npm.yaml
- package-lock.json
- package.json
- src/app/admin/xterm/xterm.component.scss
- src/app/admin/xterm/xterm.component.ts
- src/app/app.component.scss
- src/app/toolbar/toolbar.component.ts
resolves #539
maintenance task
> #539 dependency updates

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-app-server-dependabot.yaml
- .github/workflows/add-to-project-app-server.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/e2e.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications

- .github/workflows/docker-push-containers-to-dockerhub.yaml
> fix docker push

- Dockerfile
- angular.json
- package.json
- run/webserver/index.js
resolves #636 
Webserver in docker container is looking in the wrong place for it's view template.
fixes the view error.
> #636 The SSR View Template is missing for the docker container

- .github/renovate.json
> #656 disable dependency dashboard
