Dockerfile

runs the `npm run build:docker` during image build so that it's available by default startup.

docker fix

---

docker-compose.yaml
docker-stack-ssl-basicauth.yml
docker-stack-ssl.yml
docker-stack.yml

#108 
prevent possible breakage when using the compose examples against pre-release 2.0.0 api server.

use api server version env var OR fallback to 1.8.3 #108

---

CHANGELOG.md
Dockerfile
package.json
run/runtime.datastore.config.js
run/runtime.datastore.js
run/webserver/index.js
src/app/app.module.ts
src/app/services/admin.service.ts
src/app/services/ag.service.ts
src/app/services/config.service.ts

resolves: #147 
to support virtual directory paths needed for AWS Cloud Formation
The configuration can now be told to serve the application from a non-root directory by setting an env var or a cmd line switch via:
```
SENZING_WEB_SERVER_VIRTUAL_PATH: /app
```
and as a command line argument: `virtualPath="/app"`
You will also need to set the admin area's authentication path to include the virtual directory otherwise all auth conf checks will deny access to the /admin area. If running in a secured or gated configuration the `/app/admin` sections security can be turned off by setting `SENZING_WEB_SERVER_ADMIN_AUTH_MODE=NONE`
The relevant set of configuration variables would look like:
```
SENZING_WEB_SERVER_VIRTUAL_PATH: /app
SENZING_WEB_SERVER_ADMIN_AUTH_PATH: …
```

Virtual Directory Support

---

CHANGELOG.md
package-lock.json
package.json
src/app/scss/styles.scss
src/index.html
src/index.prod.html
src/main.ts

resolves #154 
material icons and roboto web fonts were unable to load in air-gapped environments

Issue154.awinters.1

---

src/app/services/config.service.ts

resolves #165 
making the code dynamically pull the path that api calls should be made to(see #163 #164 ) borked local development when not using production/docker express server
failed calls to `/config/api` (which don't exist when running angular development server) return a default payload/basepath of `/api`

#165 fix for local dev api conf issue

---

run/runtime.datastore.config.js
run/utils.js
run/webserver/index.js
run/websocket-proxy/index.js
src/app/admin/load/load.component.html
src/app/admin/load/load.component.ts
src/app/common/models/AdminStreamConnection.ts
src/app/common/stream-abort-dialog/stream-abort-dialog.component.ts
src/app/common/stream-conn-dialog/stream-conn-dialog.component.ts
src/app/common/stream-load-errors-dialog/stream-load-error-collapseable.component.ts
src/app/common/stream-load-errors-dialog/stream-load-errors-dialog.component.ts
src/app/common/stream-load-queue-dialog/stream-load-queue-dialog.component.ts
src/app/common/stream-load-queue-dialog/stream-load-queue-info.component.ts
src/app/common/url-utilities.ts
src/app/services/about.service.ts
src/app/services/admin.bulk-data.service.ts
src/app/services/config.service.ts
src/app/services/websocket.service.ts

resolves #192 
To support the web client opening up a websocket connection to an address that is different from the container host, ie: `wss://loadbalancer.gateway/app/ws` (external) ~> `ws://${internalFormationTunnel}:5255/app/ws` (internal)
Ability to route websockets over secure gateway like cognito.
There are two new variables that are being added:
- `SENZING_WEB_SERVER_STREAM_CLIENT_URL` which is that *_public_* url that the user's browser tries to open up a connection to. This overrides the default which is to use `ws://SENZING_WEB_SERVER_URL` and if that isn't set it defaults to whatever is pulled from `ws://${hostname}:${port}${virtualDir}`. Sometimes it's necessary to open up a socket to an address that is external to the webapp that round-robbins.
- …

Issue192.awinters.1

---

src/app/admin/admin-routing.module.ts
src/app/admin/admin.module.ts
src/app/admin/bulk-data/admin-bulk-data-analysis-report.component.html
src/app/admin/bulk-data/admin-bulk-data-analysis-report.component.scss
src/app/admin/bulk-data/admin-bulk-data-analysis-report.component.ts
src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.html
src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.scss
src/app/admin/bulk-data/admin-bulk-data-stream-analysis-report.component.ts
src/app/admin/datasources/datasources.component.html
src/app/admin/datasources/datasources.component.scss
src/app/admin/datasources/datasources.component.ts
src/app/admin/entity-types/entity-types.component.html
src/app/admin/entity-types/entity-types.component.scss
src/app/admin/entity-types/entity-types.component.ts
src/app/services/about.service.ts
src/app/services/admin.bulk-data.service.ts
src/app/services/config.service.ts

resolves #190 
- Per demo feedback the option to "re-map/map" **_entity-types_** found during import analysis flow has been removed.
- Per demo feedback if file contains a _**entity type**_ attached to a record and the _**entity type**_ does **_NOT_** already exist it is auto-created.
- Per demo feedback if file contains a **_datasource_** attached to a record and the **_datasource_** does not already exist it is auto-created on load phase.
- Per demo feedback if file has records that do not contain datasources attached to the record then the user will be prompted to enter a new one or select from the pre-existing options. 
- A new "entity types" route has been created solely for debug and is not exposed through UI.
UX

Removal of "entity types" mapping and "datasource" UX remapping adjustments

---

src/app/services/websocket.service.ts

resolves #196 
Stream-loading in aws exposed a missing bit of code in the offline message processing method. This missing code was responsible for enforcing that the messages sent to the websocket **_always_** ended with a **linebreak** char. Without that linebreak char the `poc-server` didn't know where one record starts/ends when the format is `json-l`
stream loading will not function properly without that linebreak char being added.

Issue196.awinters.1

---

src/app/admin/errors/no-admin.component.scss
src/app/services/admin.service.ts
src/app/services/ag.service.ts

resolves #202 
To fix a `/admin` route authentication issue when `enableAdmin` not set and user explicitly sets admin authentication to `NONE`
Redirects the user to the proper error page when `enableAdmin` not set to true regardless of whether or not admin authentication is set to `NONE`

Disable admin no auth issue.awinters.1

---

src/app/services/admin.bulk-data.service.ts

resolves #204 
When a user successfully loads a file through SQS, and then attempts to load another file without a page refresh the state of `.complete` is not fully cleared out of the load summary object resulting in a premature disconnection.
user can load more than one file

#204 debug

---

Dockerfile
package.json
run/runtime.datastore.config.js

resolves #209 
slim down the production package
- production image switched to `node:lts-alpine`
- container image size goes from 1.62GB -> 620MB
- dependency vulnerabilities greatly reduced. (`node_modules` excluding dev dependencies)
- apt-get of google-chrome removed. It is needed for e2e testing, but it adds substantial attack surface. removing it for now, we'll split off e2e testing in a different way (one that doesn't require baking chrome in to the production container)

webapp keto

---

run/runtime.datastore.config.js
run/runtime.datastore.js
run/webserver/index.js
src/app/about/about.component.html
src/app/about/about.component.ts
src/app/services/config.service.ts

resolves #235 
possibly resolves #233 
by default the application queries `/conf/package` for information about the application(dependency versions etc) if not configured properly no information will be available to display. (see screenshot)
by default the application queries `/conf/streams` for information about the ability of the pocServer to support SQS if not configured properly no information will be available and the application will not enable SQS.
- Stream loading
- About box
should now render as

misconfiguration of '/conf' paths by default

---

src/app/admin/admin-console/admin-console.component.html
src/app/admin/admin-console/admin-console.component.scss
src/app/admin/admin-console/admin-console.component.ts
src/app/admin/admin-routing.module.ts
src/app/admin/xterm/xterm.component.html
src/app/admin/xterm/xterm.component.scss
src/app/admin/xterm/xterm.component.ts
src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/app.module.ts
src/app/common/no-decoration/no-decoration.component.html
src/app/common/no-decoration/no-decoration.component.ts
src/app/services/ui.service.ts

resolves #249 
@jbutcher21 requested the ability to pop the console out of the page. seemed reasonable.
console can be operated separately from the main window. when #250 is fully implemented the user should be able to click on urls in the eda tools and have them open up in the main window or separate windows.

#249 added console pop-out functionality

---

src/app/graph/graph.component.scss
src/app/services/admin.bulk-data.service.ts
src/app/workers/stream-reader.worker.ts

resolves #252 
`json-lines` file loading was using older method of pre-parsing data before sending it to poc-server which was resulting in messages per-record with no newline char at the end of the message which the poc server would not correctly parse.
json-lines file loading

#252 json files now use onChunkRead instead of onRecordRead

---

Dockerfile

resolves #282 
the auto update script seems to fumble when the `Dockerfile` in the repo has a multi-stage build using different images for different stages. Also the base is a [`nodejs` baseimage](https://hub.docker.com/_/node), not the regular debian image(s). `Dockerfile` updated to newer 11.x debian images.
`BUILD_IMAGE` updated to `node:16-bullseye-slim`
`PROD_IMAGE` updated to `node:16-alpine3.15`
`TEST_IMAGE` updated to `node:16-bullseye-slim`

update Dockerfile FROM

---

Dockerfile
package.json
run/runtime.datastore.config.js
run/utils.js
run/webserver/index.js
run/websocket-proxy/index.js

resolves #285 
To allow docker formations to not specify a publicly available FQDN. With a reverse proxy in place the docker config can just specify the container network name, and the client can just reference **_localhost with a different port_** that forwards the socket to the console server network url(if enabled)
This simplifies adding the `senzing/entity-search-web-app-console` docker container to the `docker-compose-demo` examples since it will no longer require knowledge of the specific FQDN address.
With this change the docker formation yaml can just specify a variable pointing to the *local* name of the console container image. ie:

Add reverse socket.io proxy to webapp configuration

---

run/runtime.datastore.config.js
run/webserver/index.js
run/websocket-proxy/index.js
src/app/common/url-utilities.ts
src/app/services/config.service.ts

resolves #285 
so, turns out it still required the docker configuration to specify the `SENZING_WEB_SERVER_URL` since it would pull from that as a fallback when not specifying the `SENZING_CONSOLE_SERVER_URL`.
- Changed it so that it will default to `localhost` when **_NEITHER_** variables are specified. that way if you're just doing a POC or dev work it will most likely work out of the box. You'll have to specify one(or both) for instances where it's running off it's own domain name(not on localhost) or in the cloud or on a vhost.. which if you're doing that you should expect some configuration anyways.
- Also added some better error handling while I was in there.
- Refactored url utility functions to use a better approach

285.awinters.2

---

run/runtime.datastore.config.js
run/webserver/index.js
src/index.html

resolves #289 
changed default console server proxy from `8273` to `8257`
conforms with our default port ranges( `8250-8265` )

changed default console server proxy from `8273` to `8257`

---

.github/workflows/cd-pr-test-debian-build.yml
CHANGELOG.md
Dockerfile
package-lock.json
package.json
src/app/graph/graph.component.html
src/app/graph/graph.component.ts

resolves #321 
to fix the large graph match key token filters
bugfix

Issue321.awinters.1

---

src/app/detail/detail.component.spec.ts
src/app/graph/graph.component.spec.ts
src/app/graph/graph.component.ts

resolves #415
to stop CI pipelines with unpinned jasmine versions from throwing

#415 dummy expectations to stop jasmine from throwing in CI pipeline

---

.github/workflows/test-npm.yaml
package-lock.json
package.json

resolves #485 
The protractor testing framework reached it's EOL in august 2023. The recommendation is to discontinue use pending a e2e migration strategy to be re-implemented using the default angular@16 defaults(if there is any)

#485 removed protractor
